version: '2'
services:
  postgres:
    image: postgres:10.7
    container_name: srv-postgres
    ports:
     - "5432:5432"
    environment:
         POSTGRES_PASSWORD: "postgres"
    volumes:
      - $HOME/repositorio/volumes/postgres/backup:/volume
      - $HOME/repositorio/volumes/postgres/data:/var/lib/postgresql/data

