version: '2'
services:
  postgres:
    image: postgres
    container_name: srv-postgres
    ports:
     - "5432:5432"
    environment:
         POSTGRES_PASSWORD: postgres
    volumes:
      - $HOME/repositorio/volumes/postgres/backup:/volume
      - $HOME/repositorio/volumes/postgres/data:/var/lib/postgresql/data


  clinica:
    image: REPOSITORY/padrao:clinica-2.1
    container_name: srv-clinica
    ports:
     - "8080:8080"
    environment:
        SERVER_PORT: 8080
        SPRING_PROFILES_ACTIVE: prod
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/clinica
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: postgres
        JAVA_OPTS: "-Xms512m -Xmx640m"
    mem_limit: 768m
    restart: unless-stopped
    links:
    - postgres:postgres
    depends_on:
    - postgres


